version: '3.8'

services:
  app:
    image: node:20.16
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: sh -c "./wait-for-it.sh db:3306 -- npm run build && npm run start"
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: image_analyzer
      MYSQL_USER: root
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./app/external/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    ports:
      - '3306:3306'

volumes:
  db_data:
