# version: '3.8'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=image_analyzer
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./app/external/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
  app:
    depends_on:
      - mysqldb
    # image: node:20.16
    container_name: node_app
    # working_dir: ./
    volumes:
      - ./:/usr/src/app
    command: ["sh", "-c", "./scripts/wait-for-it.sh mysqldb:3306 -- npm install && npm run build && npm start"]
    # command: sh -c "npm install && npm run build && npm run start"
    ports:
      - '3000:3000'
    build: ./
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=image_analyzer
    stdin_open: true
    tty: true

volumes: 
  db_data:
